### PR TITLE
Joined table inheritance and Single table inheritance

### PR DESCRIPTION
**Pull request by roxblnfk**
Related: #116 #151
Also #183 : not nullable RefersTo will be converted into BelongsTo

Readme: https://gist.github.com/roxblnfk/0376dc7f1eec34262994fda3d4cdef36

### CODE REVIEW

**Review by wolfy-j — APPROVED** [review]

**Comment by guilhermeaiolfi** [comment]
Wont v2.0 support php 7.4?

**Comment by roxblnfk** [comment]
> Wont v2.0 support php 7.4?

Don't support. Is this critical for you?

**Comment by guilhermeaiolfi** [comment]
I don't know it yet. My app is using 7.4, I'll have to investigate if I decide to migrate to v2.0 in the future. But JTI is something I was looking forward to use, so most probably I'll have to bite the bullet in this one.

**Comment by roxblnfk** [comment]
Now I am looking forward to the feedback about JTI :D

**Pull request merged**
