### PR TITLE
add possibility for customization default repository in all schema roles

### PR DESCRIPTION
**Pull request by mrakolice**
Usage: 

``$orm = $orm->withRepository(CustomRepository::class);``

### CODE REVIEW

**Comment by wolfy-j** [comment]
FYI, not forgotten. The vacations end on Monday.

**Comment by wolfy-j** [comment]
I wonder if it makes sense to set the repository on the schema level. This way we can apply calculation only once.

**Comment by mrakolice** [comment]
In some cases methods in default repository are not enough, and I want to extend default behaviour for all entities I have, without defining repository on entity level.

**Comment by mrakolice** [comment]
And I think that all default values (and classes too) should be able to configure, because they are used like constants, in fact.

**Comment by wolfy-j** [comment]
I agree. I mean use Schema class instead since it's the source of all configuration.

**Comment by mrakolice** [comment]
I think this solution is not comfortable in current architecture. ``Schema->define`` function doesn't seem to be expandable for this issue. At least without some "default" role where Mapper\Repository\Constrains\etc would be store.

**Comment by wolfy-j** [comment]
What I mean is something like that:

```php
$orm->withSchemaDefaults([
   Schema::REPOSITORY=>SomeRepository::class,
   Schema::DATABASE=>'some database'
])->withSchema($schema)
```

Then you are no longer required to define these values in the schema. What do you think?

**Comment by mrakolice** [comment]
Looking very nice and simple. =) I will fix it tomorrow.

**Pull request closed without merging**
