### PR TITLE
Proxy objects and Custom collections

### PR DESCRIPTION
**Pull request by roxblnfk**
https://gist.github.com/roxblnfk/de8f3663f4f032e315558406cc997ba3

### CODE REVIEW

**Review by wolfy-j — APPROVED** [review]

**Comment by drupol** [comment]
Hi,

I'd like to add support (or at least documentation) for a custom collection: https://github.com/loophp/collection

Where is the best place to document this?

**Comment by wolfy-j** [comment]
https://github.com/cycle/docs Any help will be appericated.

**Comment by drupol** [comment]
I saw that already but the documentation that is in the [gist](https://gist.github.com/roxblnfk/de8f3663f4f032e315558406cc997ba3) on the top is not in the documentation.

Is it something that needs to be done or it is me missing something?

Thanks.

**Comment by roxblnfk** [comment]
Current documentation about Cycle v1.
This PR for v2 that was nor released yet.

**Pull request merged**
