### PR TITLE
Add compact usage

### PR DESCRIPTION
**Pull request by vvval**

### CODE REVIEW

**Comment by rauanmayemir** [comment]
I personally think that use of `compact` is not a good practice, and it's better to write it explicitly.

**Comment by rauanmayemir** [comment]
Mainly because it's hard to visually catch if something's missing, at least when written explicitly IDE will tell you.

**Comment by wolfy-j** [comment]
Same, not such what we achieve using this PR.

**Comment by wolfy-j** [comment]
Sorry Val, not this time.

**Pull request closed without merging**
