### PR TITLE
Hotfix: BelongsTo has non-cascade behavior but configured as cascade

### PR DESCRIPTION
**Pull request by roxblnfk**
- [x] add test case
- [x] fix

### CODE REVIEW

**Comment by roquie** [comment]
Any news?

**Comment by roxblnfk** [comment]
> Any news?

I will deal with it right now.

**Comment by roxblnfk** [comment]
Released in `2.1.2` and will be released in `2.2.1`.

**Comment by roquie** [comment]
Pay attention, an update can corrupt existing projects. We switched to branch with that fix and have problems with nullable `BelongsTo` properties (which not declared like nullable inside attribute but have nullable type) and deal with `ShadowBelongsTo` exception in transaction.

With 2.2.0 version we don't have bugs in these places.

**Comment by roxblnfk** [comment]
@roquie can you give more details?

**Comment by roxblnfk** [comment]
@roquie can you check the current `2.x` branch works fine?
https://github.com/cycle/orm/pull/374 adds new relation behavior

**Pull request merged**
